name: Url-checker tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test-password-strenght:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Setup dependencies
        uses: npm install

      - name: Run password strength tests
        uses: npm test --tests/Password.test.ts


